export enum NotificationType {
  PROMOTION = 'PROMOTION',
  ALERT = 'ALERT',
  REMINDER = 'REMINDER',
  SYSTEM = 'SYSTEM',
}

export enum ActivityType {
  BOOKING_CANCELED = 'BOOKING_CANCELED',
  BOOKING_NEW = 'BOOKING_NEW',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PARKING_LOT_CREATED = 'PARKING_LOT_CREATED',
  PARKING_LOT_UPDATED = 'PARKING_LOT_UPDATED',
  PARKING_LOT_DELETED = 'PARKING_LOT_DELETED',
  WALLET_DEPOSIT = 'WALLET_DEPOSIT',
  WALLET_WITHDRAW = 'WALLET_WITHDRAW',
}
